### PR TITLE
Switch to using LazyArtifacts

### LINKED ISSUE #11: Precompiling failure in windows for COPT version 5
Thank for your excellent work. It seems that `COPT.jl` can not be compiled in windows. Logs are as follows:
```
julia> using COPT
[ Info: Precompiling COPT [227a2e2d-e949-4d8e-a1da-7384fe6f0b9f]
ERROR: LoadError: Cannot locate artifact 'copt' for x86_64-w64-mingw32-libgfortran5-cxx11-julia_version+1.7.2 in 'F:\Code\Julia\Julia-1.6.2\jpkgs\.julia\packages\COPT\SFje5\Artifacts.toml'
```
my versioninfo
```
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH = F:\Code\Julia\Julia-1.6.2\jpkgs\.julia;F:\Code\Julia\Julia-1.6.2\local\share\julia\;F:\Code\Julia\Julia-1.6.2\share\julia;
  JULIA_MPI_PATH = F:/Code/MPI
  JULIA_NUM_THREADS = 4
```
谢谢！杉树求解器安装成功了，license也配置过了, python接口测试成功了, Julia不行。

### PR DESCRIPTION
**Pull request by odow**
Closes #11 

@Song921012, can you try:
```Julia
import Pkg
Pkg.pkg"add COPT#od/lazy-artifact
Pkg.build("COPT")
using COPT
```

### CODE REVIEW

**Comment by Song921012** [comment]
Thank you! Still not work. It said
image

**Comment by odow** [comment]
Hmm. Can you try exiting Julia and starting a new session? I don't have a Windows computer, so this is a little tricky for me to debug locally.

**Comment by Song921012** [comment]
Still not work. Maybe my personal issue.

**Comment by odow** [comment]
Do you have time for a Zoom call? It's probably the easiest way to debug things. https://us06web.zoom.us/j/83480517680

One thing I see wrong is that you have Julia v1.6.2 in your path, but it's looking for v1.7.2?

**Comment by odow** [comment]
@Song921012 can you try again now?

**Comment by Song921012** [comment]
Appreciate your help. It now works.

**Comment by odow** [comment]
Okay great. Today I learnt something about how Julia expands artifact string macros at the top-level when an artifact doesn't exist! 

For future readers, the problem was that `artifact"copt"` was trying to find the artifact because it was being evaluated at precompile time in the top-level scope, even though at runtime the branch would never be taken. The fix is to use `@static` which only evaluates the branch if the check is true at parse time (which effectively makes the branch disappear on systems which fail the check).

**Comment by odow** [comment]
Once this is merged, you can switch back to the normal release of COPT. The easiest way to do it is just to `] rm COPT` and the re-add.

**Pull request merged**
