### PR TITLE
Add preliminary support for v6.5.x

### PR DESCRIPTION
**Pull request by mzy2240**

### CODE REVIEW

**Comment by mzy2240** [comment]
@odow @COPT-Public @lschork2

**Comment by joachimdahl** [comment]
There are still additional features we need to port to the 6.5 interface.

**Comment by mzy2240** [comment]
A few new features that are not supported in this PR:

- native logic constraints (AND/OR/ABS/MAX/MIN/PWL) that are introduced in the new COPT Python interface
- callback functions to dynamically add lazy constraints and user cuts in MIP

**Comment by mzy2240** [comment]
I think this PR is good to go for the preliminary support of 6.5.x. At least the current users will be able to use their previous code with this new version. For new features, an additional PR is better for the purpose. Additionally, we would like to get some advices from @odow about adding lazy constraint and user cut (and the necessity/insight of supporting native logical constraints).

**Comment by odow** [comment]
> Additionally, it would be more than awesome to get some advices from @odow about adding lazy constraint and user cut

Just follow CPLEX.jl and Gurobi.jl. We've typically added a way to write solver-dependent callbacks using whatever syntax you like. And then `LazyConstraintCallback` and `UserCutCallback` are special cases.

> (and the necessity/insight on supporting native logical constraints).

Not necessary and no insight. We haven't added this to Gurobi.jl. Advanced users can access the C API if they desire. But it's something that isn't easy to abstract across solvers.

**Comment by odow** [comment]
Seems like this can be closed now that #23 is merged

**Comment by joachimdahl** [comment]
This pull request is superseded by #24 , so I am closing this.

**Pull request closed without merging**
